---
title: "Practical Machine Learning Course Project"
author: "Kapil Marwah"
date: "August 10, 2019"
output: html_document
Data Source: http://web.archive.org/web/20161224072740/http:/groupware.les.inf.puc-rio.br/har
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load important libraries and read the training data

```{r training, echo = FALSE}
library(caret)
trainingRead <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv")
head(trainingRead)
```
##Data Cleaning 
 Remove the columns having only NA values

```{r cleaning, echo=FALSE}
training_withoutna <- trainingRead[,(colSums(is.na(trainingRead)) == 0)]
dim(training_withoutna)
head(training_withoutna)
```
##Remove near Zero variance columns
```{r zerovar, echo=FALSE}
training_nonzerovariance <- training_withoutna[,-nearZeroVar(training_withoutna)]
dim(training_nonzerovariance)
head(training_nonzerovariance)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
